### ISSUE TITLE
poor performance on FUNSD

### ISSUE THREAD

**Issue by EmperorKaiser** [clovaai/spade#10]
Hi author, I tried to run the code on funsd dataset, using the given config
[funsd.1.5layers.train.zip](https://github.com/clovaai/spade/files/7684561/funsd.1.5layers.train.zip)
. But I got a poor f1 score...
The test score dict is as follows:
{
    "test__avg_loss": 0.7166563868522644,
    "test__f1": -1,
    "test__precision_edge_avg": 0.14041860174087156,
    "test__recall_edge_avg": 0.05718078420725836,
    "test__f1_edge_avg": 0.07420206034220918,
    "test__precision_edge_of_type_0": 0.19155148919602882,
    "test__recall_edge_of_type_0": 0.10966232029421598,
    "test__f1_edge_of_type_0": 0.13947554925584693,
    "test__precision_edge_of_type_1": 0.08928571428571429,
    "test__recall_edge_of_type_1": 0.004699248120300752,
    "test__f1_edge_of_type_1": 0.008928571428571428,
    "p_r_f1_entity": [
        [
            0.10144927536231885,
            0.05737704918032787,
            0.07329842931937174
        ],
        [
            0.6223404255319149,
            0.43454038997214484,
            0.5117550574084199
        ],
        [
            0.5880149812734082,
            0.38246041412911086,
            0.46346863468634686
        ],
        [
            0.46938775510204084,
            0.22115384615384615,
            0.30065359477124187
        ]
    ],
    "p_r_f1_all_entity_ELB": [
        0.5712383488681758,
        0.36792452830188677,
        0.4475743348982785
    ],
    "p_r_f1_link_ELK": [
        0.25,
        0.004699248120300752,
        0.00922509225092251
    ]
};

The main difference may be that I train the model on a single-gpu machine for 2500 epoches. I also run the preprocess code for funsd offerred in this repo. However the result on CORD dataset is close to that have been reported in the paper, the test score dict is:
{
    "test__avg_loss": 0.08372728526592255,
    "test__f1": 0.9101991060544494,
    "test__precision_edge_avg": 0.932888658103816,
    "test__recall_edge_avg": 0.9192414351541544,
    "test__f1_edge_avg": 0.9259259429039002,
    "test__precision_edge_of_type_0": 0.9672624647224836,
    "test__recall_edge_of_type_0": 0.9710993577635059,
    "test__f1_edge_of_type_0": 0.9691771137713262,
    "test__precision_edge_of_type_1": 0.8985148514851485,
    "test__recall_edge_of_type_1": 0.8673835125448028,
    "test__f1_edge_of_type_1": 0.882674772036474
}.

Would you please give me some advice how I can improve the score on the funsd IE task? The attached zip file is my trainning config.

**Comment by whwang299** [comment]
Hi @EmperorKaiser 

If you have used the default train config, `funad.1.5layers.train.yaml`, please change `toy_data: true` -> to `toy_data: false`.

https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/configs/funsd.1.5layers.train.yaml#L79.

**Comment by surelyee** [comment]
> Hi @EmperorKaiser
> 
> If you have used the default train config, `funad.1.5layers.train.yaml`, please change `toy_data: true` -> to `toy_data: false`.
> 
> https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/configs/funsd.1.5layers.train.yaml#L79
> 
> .

In this way, the training speed is very slow

**Comment by unleft** [comment]
I was getting the same problem with "toy_data: true" enabled, so I changed it as instructed and trained it again to compare the results. After 5 days of rather agonizing wait, I finally managed to train the model on funsd dataset. The "validation score" on the console output was somewhat promising nearing the end, as shown below:

Validation result at epoch 1999
{
    'validation__avg_loss': 0.002040294697508216, 
    'validation__f1': 0.5,
    'validation__precision_edge_avg': 0.9688680171966553,
    'validation__recall_edge_avg': 0.9991896152496338,
    'validation__f1_edge_avg': 0.9835796356201172,
    'validation__precision_edge_of_type_0': 0.9967637658119202,
    'validation__recall_edge_of_type_0': 0.9983792304992676,
    'validation__f1_edge_of_type_0': 0.997570812702179,
    'validation__precision_edge_of_type_1': 0.9409722089767456,
    'validation__recall_edge_of_type_1': 1.0,
    'validation__f1_edge_of_type_1': 0.9695884585380554
}

But whenever I run the test_funsd.sh script the results saved on test_score_dict are as follows:

{
    "test__avg_loss": 0.7552362084388733,
    "test__f1": -1,
    "test__precision_edge_avg": 0.14870376813234742, 
    "test__recall_edge_avg": 0.07441387445544653, 
    "test__f1_edge_avg": 0.09919069560047562, 
    "test__precision_edge_of_type_0": 0.23957171536917243, 
    "test__recall_edge_of_type_0": 0.11969241056502841, 
    "test__f1_edge_of_type_0": 0.15963139120095124, 
    "test__precision_edge_of_type_1": 0.05783582089552239, 
    "test__recall_edge_of_type_1": 0.02913533834586466, "test__f1_edge_of_type_1": 0.03875, 
    "p_r_f1_entity": [[0.23255813953488372, 0.08196721311475409, 0.12121212121212119], [0.6824925816023739, 0.4271123491179202, 0.5254140491147915], [0.6892177589852009, 0.39707673568818513, 0.5038639876352397], [0.3717948717948718, 0.09294871794871795, 0.14871794871794874]], 
    "p_r_f1_all_entity_ELB": [0.6506309148264984, 0.35377358490566035, 0.45833333333333326], 
    "p_r_f1_link_ELK": [0.16062176165803108, 0.02913533834586466, 0.049323786793953855]
}

I also cannot seem to find the code for predictions/inference for funsd to see if the evaluation is actually correct, I don't think I can apply predict_cord.sh script to funsd as well... Could you give me some advice on the matter? Thanks in advance.

**Comment by whwang299** [comment]
Hi @unleft 

Could you upload your config file?
