### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by MinhQuang2021** [clovaai/spade#11]
Hi 
I find the class data in CORD is unbalanced, the menu classes take up a lot, does this affect the result? Do you have any way to deal with this imbalance? I am very interested in this project. Thank you for sharing your knowledge
![image](https://user-images.githubusercontent.com/91367856/147526253-e82c6fb8-2885-46c9-bb0e-e9ec80ba68fc.png)

**Comment by whwang299** [comment]
Hi @MinhQuang2021 

You can use different weights for individual classes if you use cross-entropy loss.
However, I found it was not necessary at least for the CORD task. 
You may check the Table 2 of [this paper](https://openreview.net/pdf?id=SJgjf695UB) where the model is trained with 800 receipts. 

Wonseok
