### ISSUE TITLE
Data directory additional information

### ISSUE THREAD

**Issue by thomassajot** [clovaai/spade#14]
The `data.tar.gz` from https://drive.google.com/file/d/1863IJuyxFh82wTfxrUQ-Jk5NTTbHYsfK/view contains a few files and different level of distorted images.

![image](https://user-images.githubusercontent.com/15252203/148754839-c3f1d6d8-70f6-4b48-a977-df2400d00c94.png)

Are the image ids from `test_type0.jsonl` related to the images in`imgs/distorted/receipt_ind_cord_lvl1.config.json`, and the image ids from `test_type1.jsonl` related to the images in`imgs/distorted/receipt_ind_cord_lvl2.config.json` ? 

Could you provide more information on this dataset and its structure. 

I am trying to overlay the prediction of the model with the associated image from this dataset. 

Also, What is the difference between `test_type1.jsonl`, `op_test_type1.jsonl`, `op_test_plus_type1.jsonl` and `op_test_plus_plus_type1.jsonl` ?

**Comment by thomassajot** [comment]
Displaying the test text boxes over the image in lv1 and lv2. it seems the text boxes are extracted from the undistorted image. 
![image](https://user-images.githubusercontent.com/15252203/148771620-416aea50-aba4-4558-9840-6a763b81dbfb.png)
![Uploading image.png…]()

**Comment by whwang299** [comment]
Hi @thomassajot 

Yes. For the distorted receipt images, we only have their corresponding parses (i.e. structured information something like {"menu.nm": "Kimchi pizza", "menu.price": 9000}) which are identical with the original one.

Wonseok

**Comment by thomassajot** [comment]
I see thanks.
