### ISSUE TITLE
custom model

### ISSUE THREAD

**Issue by MinhQuang2021** [clovaai/spade#15]
Hello, My goal want to extract entity information without using entity association task. Can you suggest me how to do it? I find that the association in my problem is unnecessary, maybe incorrect compared to the hashcode, I just want to stop at the entity get level.
Thanks you

**Comment by whwang299** [comment]
Hi @MinhQuang2021 

You may just use `pr_f_parses` .
https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/spade/model/model.py#L309

This variable represents the set of parses before grouping.

Best,

Wonseok
