### ISSUE TITLE
Standalone evaluation

### ISSUE THREAD

**Issue by AruniRC** [clovaai/spade#19]
Hi, 

thanks for sharing the codebase!

Request: do you have standalone evaluation code, that is not part of the PyTorch lightining way of implemeting the evals? I.e., if I  have predictions dumped on file, right now it is quite tedious to get evaluation numbers (f1 etc) for them - the eval code and the modeling code are very tightly combined in your codebase. Do you have any standable evaluation script that can take in dumped predicted parses, match against GT, and give the CORD test evaluation numbers? This will make comparisons with your method much easier.

thank you,
Aruni

**Comment by whwang299** [comment]
Hi @AruniRC 

Good point. Unfortunately, not. However, you may use `cal_f1_score` (see below).
https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/spade/model/model_utils.py#L694-L699

Wonseok

**Comment by AruniRC** [comment]
Hi @whwang299 ,  thanks for the pointer to your code. This is indeed sufficient to use your eval protocol on other methods for apples to apples comparison.
