### ISSUE TITLE
Accuracy running codebase does not match paper

### ISSUE THREAD

**Issue by AruniRC** [clovaai/spade#22]
Hi @whwang299 ,

Running evaluation with this codebase on CORD matches the numbers in the github README: "test__f1": 0.9101991060544494

However, this does not match any of the numbers for parse prediction on CORD in the paper: checking the numbers of "CO"RD with oracle, SPADE gives 0.915, and SPADE with tail collision is 0.925.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/1054799/164505498-10d1ef64-90a3-4736-88b4-60c48e2cf954.png">

Can you please help resolve this mismatch?

thank you,
Aruni

**Comment by whwang299** [comment]
Hi @AruniRC 

This is because the numbers in Table 3 are calculated with the model with 12-layers
whereas the scores in README are from the model with 5-layers. 

Sorry for the confusion.

Wonseok
