### ISSUE TITLE
추출 항목 문의

### ISSUE THREAD

**Issue by jsh2581** [clovaai/spade#26]
안녕하세요. 좋은 연구 내용 및 소스 공개 감사합니다.

추출되는 항목 정의에 관해 궁굼한 점이 있습니다.

추출되지 않기를 원하는 OCR 결과 텍스트들은 어떻게 처리해야 하나요?
"others"같은 별도의 태그가 필요한가요?

연구 진행하셨을때 이런 문제는 없었는지, 어떻게 해결하셨는지 궁굼합니다.

**Comment by whwang299** [comment]
@jsh2581 님 안녕하세요. 

무시하셔도 되지만 텍스트 조각들이 하나의 field를 이루고 있다면 "others"로 분류하시는 것을 추천드립니다.
학습 신호를 좀더 명확히 주기 때문입니다.
(field는 "메뉴 이름", "가격" 등 ontology상의 원하는 정보추출 대상을 뜻합니다.)

만약 field내의 일부 text만 생략하길 원하신다면 무시하시는걸 추천드립니다!

**Comment by jsh2581** [comment]
친절한 답변 감사드립니다!
