### ISSUE TITLE
FUNSD 성능 관련 문의

### ISSUE THREAD

**Issue by SY-JI** [clovaai/spade#27]
안녕하세요 먼저 좋은 연구 공개해주셔서 감사합니다 :)

궁금한 사항이 있는데요

**1) Memory Error 관련**
- 먼저 답변해주신 내용들을 살펴보니 relative_attention도 학습되게 하기 위해선 메모리 24GB 되는 사양이 필요한 것으로 보입니다
- 16GB 사양의 gpu를 여러 개(multi-gpu 활용) 사용하더라도 해결하기 어려운 것인가요??

**2) FUNSD 성능 관련**
- FUNSD 성능의 경우 논문을 보면 ELB는 70초반, ELK는 41.3으로 되어 있습니다.
- no_relative_attention을 true하고 epoch은 2500으로 학습한 뒤 best 모델 기준으로 test 성능을 보면 낮게 나오는 것으로 보입니다
- 혹시 no_relative_attention 옵션의 영향인가요??
```
{"test__avg_loss": 0.2842002809047699, 
"test__f1": -1, 
"test__precision_edge_avg": 0.20648076446339075, 
"test__recall_edge_avg": 0.09938241102015245, 
"test__f1_edge_avg": 0.133308610191091, 
"test__precision_edge_of_type_0": 0.29918907383696114, 
"test__recall_edge_of_type_0": 0.1588488556537503, 
"test__f1_edge_of_type_0": 0.20751924215512135, 
edge_of_type_1": 0.11377245508982035, 
"test__recall_edge_of_type_1": 0.03991596638655462, 
"test__f1_edge_of_type_1": 0.05909797822706065, 
"p_r_f1_entity": [
[0.47058823529411764, 0.13333333333333333, 0.2077922077922078], 
[0.7303921568627451, 0.5995975855130785, 0.6585635359116022], 
[0.75, 0.556135770234987, 0.638680659670165], 
[0.5909090909090909, 0.16049382716049382, 0.2524271844660194]], 
"p_r_f1_all_entity_ELB": [0.7237715803452855, 0.4945553539019964, 0.5876010781671159], 
"p_r_f1_link_ELK": [0.27941176470588236, 0.03991596638655462, 0.06985294117647059]}
```

**3) FUNSD 예측 코드 관련**
- predict_funsd.sh의 경우 공개되지 않은 것으로 보이는데 predict_cord.sh를 가져와서 일부 변경해서 사용하면 되는 건가요??

**4) field_rs 관련**
- 추가로 궁금한 것이 있는데 field_rs를 왜 사용하는 것인지 궁금합니다.
- funsd, cord 데이터에 따라 그것이 갖는 의미도 다른 것 같습니다.
- cord에서는 서로 다른 field를 묶어줄 때 맨 앞에 와야 하는 것이기 때문에 사용하나요??
- funsd 에서는 key-value를 묶어주기 위해(question - answer 형태) question을 field_rs로 지정하는 것인가요?

감사합니다!!

**Comment by SY-JI** [comment]
4) field_rs 관련
- 추가로 궁금한 것이 있는데 field_rs를 왜 사용하는 것인지 궁금합니다.
- funsd, cord 데이터에 따라 그것이 갖는 의미도 다른 것 같습니다.
- cord에서는 서로 다른 field를 묶어줄 때 맨 앞에 와야 하는 것이기 때문에 사용하나요??
- funsd 에서는 key-value를 묶어주기 위해(question - answer 형태) question을 field_rs로 지정하는 것인가요?

**Comment by whwang299** [comment]
안녕하세요 @SY-JI 님, 답변이 늦었습니다.

1) 번의 경우 batch_size가 1일때도 학습이 되지 않을 경우, multi-gpu를 사용하셔도 현재 코드로 돌리기는 힘드실것 같습니다. [Deepspeed](https://github.com/microsoft/DeepSpeed) 등의 library를 참고하여 custom하게 코드를 수정하시거나, [BROS](https://github.com/clovaai/bros) 를 참고하셔서 relative attention 계산을 좀더 효율적으로 해보시면 될것 같습니다!

2) 번 관련하여, relative attention을 끌 경우 성능이 떨어지긴 하지만 그럼에도 불구하고 많이 낮아 보이네요.  아래 코드 참고하셔서 절대 좌표값이 들어가고 있는지 확인해 보시면 좋을것 같습니다. (`- base` -> `- absPos`로 변경)
https://github.com/clovaai/spade/blob/e747917ab8f5f00acffa16ef5897fc09514da40f/configs/funsd.1.5layers.train.yaml#L20

사용하신 gpu개수에 따라 `train_param/accumulate_grad_batches`를 조절하셔서 batch_size를 조절해 보실수 있을것 같습니다 (그때 당시 P40 6대로 재현 실험을 함).

3) 넵

4) SPADE는 정보 계층 별로 parse를 묶어 주고, 그 과정에서 각 층의 대표 field를 지정합니다. 이때 field_rs를 사용하였습니다. FUNSD의 경우(기억이 가물가물하지만..) 말씀하신대로 입니다!

황원석 드림

**Comment by SY-JI** [comment]
답변 감사합니다!
좋은 하루 보내세요!!
