### ISSUE TITLE
Data Augmentation 

### ISSUE THREAD

**Issue by amitbcp** [clovaai/spade#7]
Hi Team,

Thanks for opensourcing the project. In the paper, one of the ablations study with data augmentation leads to performance drop. Can that be check from the current code ? If yes, please let me know how to do it. Thanks in Advance

**Comment by whwang299** [comment]
Hi @amitbcp 

You can turn off by setting
`augment_data = false` (this is for the token augmentation)
`augment_coordinate = false` (this is for the (pseudo-) image rotation and warping)

https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/configs/cord.1.5layers.train.yaml#L124-L125
