### ISSUE TITLE
No output in test results

### ISSUE THREAD

**Issue by EmperorKaiser** [clovaai/spade#9]
Hi, team, It's great that you can open the source code for your excellent work. I'm trying to run the test scripts in scripts/test_cord.sh. I have only 1 GPU so I change the definition of trainer object in spade/model/run_model.py to be like:
`
trainer = pl.Trainer(
            logger=tb_logger,
            log_every_n_steps=cfg.train_param.get("log_every_n_steps", 50),
            gpus=1,
            max_epochs=cfg.train_param.max_epochs,
            val_check_interval=cfg.train_param.val_check_interval,
            limit_train_batches=cfg.train_param.limit_train_batches,
            limit_val_batches=cfg.train_param.limit_val_batches,
            num_sanity_val_steps=1,
            progress_bar_refresh_rate=100,
            accumulate_grad_batches=cfg.train_param.accumulate_grad_batches,
            precision=cfg.model_param.precision,
            gradient_clip_val=cfg.train_param.gradient_clip_val,
            gradient_clip_algorithm=cfg.train_param.gradient_clip_algorithm,
        )
`
however, I got empty results after testing iterations finished, something like
`DATALOADER:0 TEST RESULTS
{}`

I am wondering is this script suitable for single gpu training and testing?
PS: I have already downloaded the data and pretrained model and the predict script got normal outputs.

**Comment by whwang299** [comment]
Hi @EmperorKaiser 

Yes, that's why I have used `pytorch-lightning`.  Also you don't need to change `gpus=torhc.cuda.device_count()` argument.

Hm.. have you put the data under `[your-project-dir-where-main.py-is-in]/data/receipt_ind_cord_v0.1/test/test_type1.jsonl`?

**Comment by EmperorKaiser** [comment]
yes, quite weird... I think I have got the data in the right place, and the test_type1.jsonl  does contain something.
![image](https://user-images.githubusercontent.com/26653458/144437148-fbd85999-64e6-4b50-a2bd-be706b168d0e.png)
Would you please tell me in which part the code prints output log like"DATALOADER: x TEST RESULT{xxxxx}", I may check the result objects

**Comment by whwang299** [comment]
The message is from `pytorch-lightning` I guess.

Hm... 
If `test_cord.sh` runs correctly, the result will be saved under`[model-dir]/analaysis/[cfg-name]/`.
<img width="329" alt="image" src="https://user-images.githubusercontent.com/11023071/144518288-2d4a1480-9441-48f6-99f9-5ffa6bdcab78.png">

Could you check this folder?



The related code snippets are as below.
https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/spade/model/model.py#L730-L740

https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/spade/utils/config_manager.py#L26-L30

**Comment by EmperorKaiser** [comment]
Okay, I got these results. It seems that you did't return the dict result in the test_epoch_end function from model.py. So pytorch_lightening gives an empty {} in the console terminal by default, but the result has been stored as files. Thanks~
